<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ $title ?? __('Vertex Contas - User Panel') }}</title>

    <link rel="icon" type="image/svg+xml" href="{{ asset('storage/logos/favicon.svg') }}">

    <!-- Scripts -->
    {{-- Use paths matching the manifest keys generated by the module's vite build --}}
    @vite(['resources/assets/sass/app.scss', 'resources/assets/js/app.js'], 'build-paneluser')

    <!-- FontAwesome (Local) -->
    <link href="{{ asset('assets/fontawesome/css/all.min.css') }}" rel="stylesheet">

    <script>
        // On page load or when changing themes, best to add inline in head to avoid FOUC
        if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            document.documentElement.classList.add('dark');
        } else {
            document.documentElement.classList.remove('dark')
        }
    </script>
</head>
<body class="bg-gray-50 dark:bg-gray-900 font-sans text-gray-900 antialiased">
    <div class="antialiased bg-gray-50 dark:bg-gray-900 min-h-screen">

        <x-paneluser::layouts.navbar />

        <x-paneluser::layouts.sidebar />

        <main class="p-4 md:ml-64 h-auto pt-20 transition-all duration-300">
            <x-core::inspection-banner />

            {{ $slot }}

            <x-paneluser::inspection-modal />
            <x-notifications::toast />
        </main>
    </div>
    @stack('scripts')
</body>
</html>
